export const patientInit = {
  id: "",
  name: "",
  dob: "",
  age: "",
  gender: "",
  marital_status: "",
  born_city: "",
  residence: "",
  occupation: "",
  phone: "",
  email: "",
  insurance_provider: "",
  insurance_policy_number: "",
  insurance_groub_number: "",
};
export const patientMedicalHistoryInit = {
  id: "",
  patient_id: "",
  allergies: [],
  medications: [],
  conditions: [],
  special_habits: [],
  past_history: "",
  family_history: "",
  notes: "",
};
export const appointmentInit = {
  id: "",
  patient_id: "",
  complaint: "",
  present_history: "",
  examination: "",
  provisional_diagnosis: "",
  past_history: "",
  bp: "",
  p: "",
  t: "",
  rr: "",
  rbs: "",
  spo2: "",
  weight: "",
  height: "",
  prescription: [],
  created_at: new Date().toISOString(),
};

export const dumy_patient = {
  id: "342432",
  name: "John Doe",
  age: "56",
  gender: "male",
  height: "182",
  weight: "79",
  bloodPressure: `120/90`,
  heartRate: `60 `,
  temperature: `37`,
  marital: "single",
  bornCity: "Cairo",
  occupation: "Doctor",
  allergies: ["allergies"],
  specialHabits: ["smoking", "drinking"],
  medications: ["medications", "fdsf"],
  conditions: ["conditions"],
  notes: "fdsf fdsf fdsfds",
  history: [
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
  ],
  contactInfo: {
    phone: "01117834885",
    email: "test@test.com",
    address: "cairo ",
  },
  insurance: {
    provider: "xyz",
    policyNumber: "43243252524",
    groupNumber: "5235425435",
  },
};
export const patientInfoQInit = {
  patient_id: "",
  name: "",
  appointment_type: "",
  description: "",
};
