export const patientInit = {
  id: "",
  name: "",
  age: "",
  gender: "",
  height: "",
  weight: "",
  bloodPressure: "",
  heartRate: "",
  marital: "",
  bornCity: "",
  temperature: "",
  occupation: "",
  allergies: "",
  specialHabits: [""],
  medications: [""],
  conditions: [""],
  notes: "",
  history: [
    {
      date: "",
      reason: "",
      diagnosis: "",
      treatment: "",
      doctor: "",
    },
  ],
  contactInfo: {
    phone: "",
    email: "",
    address: "",
  },
  insurance: {
    provider: "",
    policyNumber: "",
    groupNumber: "",
  },
};

export const dumy_patient = {
  id: "342432",
  name: "John Doe",
  age: "56",
  gender: "male",
  height: "182",
  weight: "79",
  bloodPressure: `120/90`,
  heartRate: `60 `,
  temperature: `37`,
  marital: "single",
  bornCity: "Cairo",
  occupation: "Doctor",
  allergies: "allergies",
  specialHabits: ["smoking", "drinking"],
  medications: ["medications", "fdsf"],
  conditions: ["conditions"],
  notes: "fdsf fdsf fdsfds",
  history: [
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
    {
      date: "20/4/2000",
      reason: "any",
      diagnosis: "any",
      treatment: "any",
      doctor: "any",
    },
  ],
  contactInfo: {
    phone: "01117834885",
    email: "test@test.com",
    address: "cairo ",
  },
  insurance: {
    provider: "xyz",
    policyNumber: "43243252524",
    groupNumber: "5235425435",
  },
};
